server {
    listen 80;

    location /php/ {
            proxy_pass http://php-app:8000/; # Имя сервиса из docker-compose
        }

    location /node/ {
        proxy_pass http://node-app:3000/;
    }

    location /python/ {
            proxy_pass http://python-app:5000/;
        }
}